config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    resources :respondents, only: [:new, :create]
  end

  namespace :response do
    resources :documents do
      post 'make_decision', on: :member
    end
  end

  devise_for :users
  get 'visitors/index'
  root to: 'visitors#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :file, ::StoredFileUploader
  belongs_to :user
  has_secure_token
  attribute :manually_approved, :boolean, default: false
  validates :title, :description, presence: true
  has_many :respondents, dependent: :destroy

  accepts_nested_attributes_for :respondents
end

app/models/respondent.rb
class Respondent < ApplicationRecord
  include AASM
  belongs_to :document

  validates :name, :email, presence: true
  validates :email, uniqueness: { scope: :document_id }

  has_secure_token :access_key

  enum status: {
    pending: 0,
    viewed: 1,
    approved: 2,
    denied: 3
  }

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :viewed, :approved, :denied

    event :view do
      transitions from: :pending, to: :viewed
    end

    event :approval do
      transitions from: [:pending, :viewed], to: :approved
    end

    event :denial do
      transitions from: [:pending, :viewed], to: :denied
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :documents

  def documents_for_approval
    respondents = Respondent.where(email: email)
    approval_documents = []
    if respondents.any?
      respondents.each do |r|
        approval_documents << r.document
      end
    end
    approval_documents
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_document, except: [:index, :new, :create]

  def index
    @documents = current_user.documents
  end

  def show
  end

  def new
    @document = current_user.documents.new
  end

  def create
    @document = current_user.documents.new(document_params)
    if @document.save
      redirect_to @document, notice: 'Document created successfully!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @document.update(document_params)
      redirect_to @document, notice: 'Document edited.'
    else
      render :edit
    end
  end

  def destroy
    if @document.destroy
      redirect_to documents_url, notice: 'Document destroyed!'
    else
      render :show
    end
  end

  private

  def document_params
    params.require(:document).permit(:title, :description, :file,
                                    respondents_attributes: [:id, :name, :email, :_destroy])
  end

  def find_document
    @document = Document.find params[:id]
  end
end

app/controllers/respondents_controller.rb
class RespondentsController < ApplicationController
  before_action :set_document

  def new
    @respondent = @document.respondents.new
  end

  def create
    @respondent = @document.respondents.new(respondent_params)
    if @respondent.save
      DocumentsMailer.respondent_added(@respondent).deliver_now
      redirect_to @document, notice: 'Success!'
    else
      render :new
    end
  end

  private

  def set_document
    @document = Document.find params[:document_id]
  end

  def respondent_params
    params.require(:respondent).permit(:name, :email)
  end
end

app/controllers/response/documents_controller.rb
class Response::DocumentsController < ApplicationController
  def show
    @respondent = Respondent.find_by_access_key params[:id]
    @document = @respondent.document
  end

  def make_decision
    @respondent = Respondent.find_by_access_key params[:id]
    if params['commit'] == 'Approve'
      @respondent.approval!
      @respondent.update(decision_params)
    elsif params['commit'] == 'Deny'
      @respondent.denial!
      @respondent.update(decision_params)
    else
      raise 'Invalid commit.'
    end
      redirect_to response_document_path(@respondent.access_key)
  end

  private

  def decision_params
    params.require(:respondent).permit(:decision_comments)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    analytics.page();
    }}();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_navigation.html.slim
.top-bar
  .top-bar-left
    ul.dropdown.menu data-dropdown-menu="" 
      li.menu-text GetConsensus
      li
        = link_to 'Home', root_path
      - unless current_user
        li
          = link_to 'Login', new_user_session_path
      - else
        li = link_to 'Documents', documents_path
        li
          = link_to "#{current_user.email} (logout)", destroy_user_session_path,
            method: :delete

  .top-bar-right
    ul.menu
      li
        input placeholder="Search" type="search" /
      li
        button.button type="button"  Search

app/views/documents/_form.html.slim
= simple_form_for @document do |f|
  = f.input :title
  = f.input :description
  = f.input :file
  hr
  - unless @document.persisted?
    h2 Respondents
    #respondents
      = f.simple_fields_for :respondents do |resp|
        = render 'respondent_fields', f: resp
      .links
        = link_to_add_association 'add respondent', f, :respondents,
          class: 'button success'
  = f.submit class: 'button'

app/views/documents/_respondent_fields.html.slim
.nested-fields
  .row
    .small-9.columns
      = f.input :name
      = f.input :email

    .small-3.columns
      - unless @document.persisted?
        = link_to_remove_association "remove", f, class: 'button alert'
  hr

app/views/documents/edit.html.slim
.container
  h1 Documents#edit
  = render 'form'

app/views/documents/index.html.slim
.container
  h1 My Documents
  table
    thead
      tr
        th Title
        th Description
        th Created at
        th[colspan="3"] Actions
    tbody
      - @documents.each do |document|
        tr
          td = document.title
          td = truncate(document.description)
          td = document.created_at.strftime('%d-%b-%Y %I:%M%p')
          td = link_to 'Show', document
          td = link_to 'Edit', [:edit, document]
          td = link_to 'Destroy', document, method: :delete
  = link_to 'New Document', [:new, :document], class: 'button'

app/views/documents/new.html.slim
.container
  h1 New Document
  = render 'form'

app/views/documents/show.html.slim
.container
  h1 = @document.title
  .row
    .small-9.columns
      table
        tr
          th Title
          td = @document.title
        tr
          th Description
          td = @document.description
        tr
          th Uploaded by
          td = @document.user.email
    .small-3.columns
      = link_to 'Download File', @document.file.url, class: 'button large expanded'
      //hr
      = link_to 'Edit', [:edit, @document], class: 'button warning expanded'
      = link_to 'Delete', @document, class: 'button alert expanded', 
        method: :delete, data: { confirm: 'Are you sure?' }
  h2 Respondents
  table
    thead
      tr
        th Name
        th Email
        th Status
    tbody
      - @document.respondents.each do |r|
        tr
          td = r.name
          td = r.email
          td = r.status
  = link_to 'Add Respondent', [:new, @document, :respondent], class: 'button'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = csrf_meta_tag

  body[class="#{body_class}"]
    = render 'application/navigation'
    = render 'application/flashes'    

    == yield

    = javascript_include_tag "application"

app/views/respondents/_form.html.slim
= simple_form_for [@document, @respondent] do |f|
  = f.input :name
  = f.input :email
  = f.submit 'Add Respondent', class: 'button'

app/views/respondents/new.html.slim
.container
  h1 Add Respondent
  dl
    dt Document
    dd = @document.title
  = render 'form'
  = link_to 'Go Back', @document

app/views/response/documents/_form.html.slim
= simple_form_for :respondent, 
  url: make_decision_response_document_path(@respondent.access_key) do |f|
  = f.input :decision_comments
  = f.submit 'Approve', class: 'button success'
  = f.submit 'Deny', class: 'button alert'

app/views/response/documents/show.html.slim
.container
  h3 Welcome, #{@respondent.name}!
  p <strong>#{@document.user.email}</strong> is requesting your approval for the file below:

  = link_to 'View File', @document.file.url, class: 'button'

  - unless @respondent.approved? || @respondent.denied?
    = render 'form'
  - else
    p Your decision of <strong>#{@respondent.status.upcase}</strong> has been recorded.

app/views/visitors/index.html.slim
.container
  h1 GetConsensus!
  p This is a tool used by ZDN Enterprises, LLC for acquiring approvals on files
    for customers.